before_script:
    - echo "project path" $CI_PROJECT_PATH
    - echo "cwd" `pwd`
    - echo "Checking python version ..."
    - python -V      # Print out python version for debugging
    - echo 'Setting up proxy'
    - export http_proxy=http://webbalance.inl.gov:8080;
        export https_proxy=http://webbalance.inl.gov:8080;
        export ftp_proxy=http://webbalance.inl.gov:8080;
        export ftps_proxy=http://webbalance.inl.gov:8080
    # clone raven
    # we technically still need moose for running the tests, currently
    - echo "Cloning RAVEN ..."
    - git clone https://github.com/idaholab/raven.git
    - cd raven
    - git submodule update --init moose
    - cd raven
    - git checkout master
    - git clean -xfd
      # check that we have conda
    - export PATH=/opt/miniconda2/bin:$PATH
    - if which conda 2> /dev/null; then
        echo "Conda found!";
      else
        echo "ERROR Conda not found!";
        exit 404; # TODO make some meaningful error codes
      fi
      # update libraries or create them
    - if conda env list | grep -q raven_libraries; then
        `python ~/projects/raven/scripts/TestHarness/testers/RavenUtils.py --conda-install`;
      else
        `python ~/projects/raven/scripts/TestHarness/testers/RavenUtils.py --conda-create`;
      fi
    - make
    - echo "Installing CashFlow branch ..."
    - cd scripts
    - python install_plugins.py -s ../../ -f

#build:
#    script:
#    - echo "Put your build stuff here."

test:
    script:
      #- echo "Put your test runs here."
      - cd ~/projects/raven
      - ./run_tests -j4 --re=plugins/CashFlow # does this return a failed status?
