before_script:
    - echo "Checking python version ..."
    - python -V      # Print out python version for debugging
    # clone path is at $CI_PROJECT_PATH
    - echo "Checking out RAVEN master ..."
    # enter "~/projects" if it exists; otherwise make it
    - cd ~/
    - if [ -d "projects" ]; then
        cd projects
      else
        mkdir projects
        cd projects
      fi
    # if RAVEN isn't there, clone it, install it, etc
    ## we technically still need moose for running the tests, currently
    - if [ ! -d "raven" ]; then
        echo 'Cloning RAVEN ...'
        git clone https://github.com/idaholab/raven.git
        cd raven
        git submodule update --init moose
      fi
    - cd ~/projects/raven
    - git checkout master
    - git clean -xfd
    - make
    - echo "Installing CashFlow branch ..."
    - cd ~/projects/raven/scripts
    - python install_plugins.py -s $CI_PROJECT_PATH -f

#build:
#    script:
#    - echo "Put your build stuff here."

test:
    script:
      #- echo "Put your test runs here."
      - cd ~/projects/raven
      - ./run_tests -j4 --re=plugins/CashFlow # does this return a failed status?
