before_script:
    - echo "project path:" $CI_PROJECT_PATH
    - echo "cwd:" `pwd`
    - echo "Checking python version ..."
    - python -V      # Print out python version for debugging
    - echo 'Setting up proxy'
    - export http_proxy=http://webbalance.inl.gov:8080;
        export https_proxy=http://webbalance.inl.gov:8080;
        export ftp_proxy=http://webbalance.inl.gov:8080;
        export ftps_proxy=http://webbalance.inl.gov:8080
    - echo "Checking out RAVEN master ..."
    # enter "~/projects" if it exists; otherwise make it
    - cd ~/
    - if [ -d "projects" ]; then
        cd projects;
      else
        mkdir projects;
        cd projects;
      fi
    # if RAVEN isn't there, clone it, install it, etc
    ## we technically still need moose for running the tests, currently
    - if [ ! -d "raven" ]; then
        echo "Cloning RAVEN ...";
        git clone https://github.com/idaholab/raven.git;
        cd raven;
        git submodule update --init moose;
      fi
    - cd ~/projects/raven
    - git checkout master
    - git clean -xfd
      # check that we have conda
    - export PATH=export PATH=/opt/miniconda2/bin:$PATH
    - if which conda 2> /dev/null; then
        echo "Conda found!";
      else
        echo "Error Conda not installed!";
        exit 42;
      fi
      # update libraries or create them
    - if conda env list | grep -q raven_libaries; then
        `python ~/projects/raven/scripts/TestHarness/testers/RavenUtils.py --conda-install`;
      else
        `python ~/projects/raven/scripts/TestHarness/testers/RavenUtils.py --conda-create`;
      fi
    - make
    - echo "Installing CashFlow branch ..."
    - cd ~/projects/raven/scripts
    - python install_plugins.py -s $CI_PROJECT_PATH -f

#build:
#    script:
#    - echo "Put your build stuff here."

test:
    script:
      #- echo "Put your test runs here."
      - cd ~/projects/raven
      - ./run_tests -j4 --re=plugins/CashFlow # does this return a failed status?
